CREATE TABLE Base(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
)

CREATE TABLE User(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(60)NOT NULL,
    PASSWORD VARCHAR(23)NOT NULL,
    PHONE_NUMBER INT NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL
)

CREATE TABLE Category_Establishment(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
)

CREATE TABLE Category_Product(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
)

CREATE TABLE Restaurant(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200)
    PHONE_NUMBER INT NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    RATE INT
)

CREATE TABLE Operation_Restaurant(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    DAY INT,
    OPEN TIME INT,
    CLOSING TIME INT
)

CREATE TABLE Address(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    ROAD VARCHAR(200) NOT NULL,
    NEIGHBORHOOD VARCHAR(50) NOT NULL,
    CITY VARCHAR(80) NOT NULL,
    ZIP_CODE VARCHAR(8),
    NUMBER INT NOT NULL,
    COMPLEMENT VARCHAR(130),
    PATTERN INT
)

CREATE TABLE Product(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(60) NOT NULL,
    PRICE INT NOT NULL,
    DESCRIPTION VARCHAR(200)
)

CREATE TABLE Additional(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(60) NOT NULL,
    VALUE INT,
    DESCRIPTION VARCHAR(200)
)

CREATE TABLE Product_Additional(
)

CREATE TABLE Favorite(
)

CREATE TABLE Stats_Delivery(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(80),
    DESCRIPTION(200)
)

CREATE TABLE Coupon(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    CODE VARCHAR(10) NOT NULL,
    VALUE INT NOT NULL,
    VALIDITY INT NOT NULL,
    DESCRIPTION VARCHAR(200)
)

CREATE TABLE Delivery(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    DELIVERY_FEE INT,
    AMOUNT INT,
    IS_REMOVAL INT,
    DESCRIPTION VARCHAR(200),
)

CREATE TABLE Delivery_Product(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
)

CREATE TABLE Additional_Product_Delivery(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    AMOUNT INT,
)

CREATE TABLE Rate(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    RESTAURANT_RATE INT,
    DELIVERY_RATE INT,
    DESCRIPTION VARCHAR(200)
)

CREATE TABLE Historic_Delivery(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
)

CREATE TABLE Stats_Pay(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(150),
    DESCRIPTION VARCHAR(200),
)

CREATE TABLE Method_Pay(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    NAME VARCHAR(150),
    DESCRIPTION VARCHAR(200),
)

CREATE TABLE Payment(
    ID INT PRIMARY KEY NOT NULL,
    STATS INT,
    DATA CREATE INT,
    VALUE INT NOT NULL,
    DATE_HOUR INT,
)